{"name": "test_case[case5]", "status": "broken", "statusDetails": {"message": "TypeError: 'tuple' object is not callable", "trace": "self = <test_case.Test_Case object at 0x00000255DA2EE160>\ncase = {'case_description': '/message/mark_all 标记全部已读', 'case_expect': '{\"success\":false}', 'case_method': 'post', 'case_params': '', ...}\n\n    @pytest.mark.parametrize('case',Excel_Handler().get_excel_data())\n    def test_case(self,case):\n        print(11111111111111111,case)\n>       response = RequestHandler(case).get_response()\nE       TypeError: 'tuple' object is not callable\n\nscripts\\test_case.py:14: TypeError"}, "parameters": [{"name": "case", "value": "{'case_project': 'cnodejs项目', 'case_description': '/message/mark_all 标记全部已读', 'case_url': 'https://cnodejs.org/api/v1/message/mark_all', 'case_method': 'post', 'case_params': '', 'case_expect': '{\"success\":false}', 'other': '咱们没有用户 accessToken，所以返回为false就算对'}"}], "start": 1574774795052, "stop": 1574774795475, "uuid": "e16fdb61-b5dd-4b31-b0ad-98f05cf6c933", "historyId": "6bc55cd1e7e195e1acc37ba234767a51", "testCaseId": "89a27520489a549f0caeaffa7948244d", "fullName": "scripts.test_case.Test_Case#test_case", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "Test_Case"}, {"name": "host", "value": "IG6I7Y1F5I7TZH5"}, {"name": "thread", "value": "15128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_case"}]}